export const PERMISSIONS_REQUEST_START = 'PERMISSIONS_REQUEST_START';
export const PERMISSIONS_REQUEST_SUCCESS = 'PERMISSIONS_REQUEST_SUCCESS';
export const PERMISSIONS_REQUEST_FAILURE = 'PERMISSIONS_REQUEST_FAILURE';
export const PERMISSIONS_STATUSES_SET = 'PERMISSIONS_STATUSES_SET';

export const DEVICE_GET_CONTACTS_START = 'DEVICE_GET_CONTACTS_START';
export const DEVICE_GET_CONTACTS_SUCCESS = 'DEVICE_GET_CONTACTS_SUFAILURE';
export const DEVICE_GET_CONTACTS_FAILURE = 'DEVICE_GET_CONTACTS_FAILURE';
export const DEVICE_GET_CONTACTS_SET = 'DEVICE_GET_CONTACTS_SET';
