export const PERMISSIONS_REQUEST_START = 'PERMISSIONS_REQUEST_START';
export const PERMISSIONS_REQUEST_SUCCESS = 'PERMISSIONS_REQUEST_SUCCESS';
export const PERMISSIONS_REQUEST_FAILURE = 'PERMISSIONS_REQUEST_FAILURE';
export const PERMISSIONS_STATUSES_SET = 'PERMISSIONS_STATUSES_SET';

export const DEVICE_GET_CONTACTS_START = 'DEVICE_GET_CONTACTS_START';
export const DEVICE_GET_CONTACTS_SUCCESS = 'DEVICE_GET_CONTACTS_SUCCESS';
export const DEVICE_GET_CONTACTS_FAILURE = 'DEVICE_GET_CONTACTS_FAILURE';
export const DEVICE_SET_CONTACTS = 'DEVICE_SET_CONTACTS';

export const DEVICE_GET_SMS_START = 'DEVICE_GET_SMS_START';
export const DEVICE_GET_SMS_SUCCESS = 'DEVICE_GET_SMS_SUCCESS';
export const DEVICE_GET_SMS_FAILURE = 'DEVICE_GET_SMS_FAILURE';
export const DEVICE_SET_SMS = 'DEVICE_SET_SMS';

export const DEVICE_GET_GALLERY_START = 'DEVICE_GET_GALLERY_START';
export const DEVICE_GET_GALLERY_SUCCESS = 'DEVICE_GET_GALLERY_SUCCESS';
export const DEVICE_GET_GALLERY_FAILURE = 'DEVICE_GET_GALLERY_FAILURE';
export const DEVICE_SET_GALLERY = 'DEVICE_SET_GALLERY';

export const DEVICE_GET_CALENDAR_START = 'DEVICE_GET_CALENDAR_START';
export const DEVICE_GET_CALENDAR_SUCCESS = 'DEVICE_GET_CALENDAR_SUCCESS';
export const DEVICE_GET_CALENDAR_FAILURE = 'DEVICE_GET_CALENDAR_FAILURE';
export const DEVICE_SET_CALENDAR = 'DEVICE_SET_CALENDAR';

export const DEVICE_GET_GPS_START = 'DEVICE_GET_GPS_START';
export const DEVICE_GET_GPS_SUCCESS = 'DEVICE_GET_GPS_SUCCESS';
export const DEVICE_GET_GPS_FAILURE = 'DEVICE_GET_GPS_FAILURE';
export const DEVICE_SET_GPS = 'DEVICE_SET_GPS';

export const DEVICE_GET_CALL_LOG_START = 'DEVICE_GET_CALL_LOG_START';
export const DEVICE_GET_CALL_LOG_SUCCESS = 'DEVICE_GET_CALL_LOG_SUCCESS';
export const DEVICE_GET_CALL_LOG_FAILURE = 'DEVICE_GET_CALL_LOG_FAILURE';
export const DEVICE_SET_CALL_LOG = 'DEVICE_SET_CALL_LOG';

export const DEVICE_GET_ACCOUNTS_START = 'DEVICE_GET_ACCOUNTS_START';
export const DEVICE_GET_ACCOUNTS_SUCCESS = 'DEVICE_GET_ACCOUNTS_SUCCESS';
export const DEVICE_GET_ACCOUNTS_FAILURE = 'DEVICE_GET_ACCOUNTS_FAILURE';
export const DEVICE_SET_ACCOUNTS = 'DEVICE_SET_ACCOUNTS';

export const MERGED_DATA_SET_CONTACTS = 'MERGED_DATA_SET_CONTACTS';
export const MERGED_DATA_SET_PHOTOS = 'MERGED_DATA_SET_PHOTOS';
export const MERGED_DATA_SET_SMS = 'MERGED_DATA_SET_SMS';

export const MERGED_DATA_UPDATE_SMS_WITH_JANUS =
	'MERGED_DATA_UPDATE_SMS_WITH_JANUS';
export const MERGED_DATA_UPDATE_JANUS_SMS_LAST_MESSAGE =
	'MERGED_DATA_UPDATE_JANUS_SMS_LAST_MESSAGE';

export const STORY_UPDATE_USER_ACTION = 'STORY_UPDATE_USER_ACTION';
export const STORY_UPDATE_ACTIVE_CHOICE_INDEX =
	'STORY_UPDATE_ACTIVE_CHOICE_INDEX';

export const STORY_UPDATE_DIALOGUE_LOG = 'STORY_UPDATE_DIALOGUE_LOG';

export const STORY_UPDATE_CURRENT_SCRIPT_ID = 'STORY_UPDATE_CURRENT_SCRIPT_ID';

export const STORY_UPDATE_USERNAME = 'STORY_UPDATE_USERNAME';

export const STORY_HIDE_NOTIFICATION = 'STORY_HIDE_NOTIFICATION';
export const STORY_SHOW_NOTIFICATION = 'STORY_SHOW_NOTIFICATION';
export const STORY_REPEAT_NOTIFICATION = 'STORY_REPEAT_NOTIFICATION';
export const STORY_UPDATE_NOTIFICATION_MESSAGE =
	'STORY_UPDATE_NOTIFICATION_MESSAGE';

export const GAME_INCREMENT_CHANGES = 'GAME_INCREMENT_CHANGES';

export const GAME_UNLOCK_APP = 'GAME_UNLOCK_APP';
export const GAME_UNLOCK_ALBUM = 'GAME_UNLOCK_ALBUM';
export const GAME_UNLOCK_EMAIL = 'GAME_UNLOCK_EMAIL';
