export const PERMISSIONS_REQUEST_START = 'PERMISSIONS_REQUEST_START';
export const PERMISSIONS_REQUEST_SUCCESS = 'PERMISSIONS_REQUEST_SUCCESS';
export const PERMISSIONS_REQUEST_FAILURE = 'PERMISSIONS_REQUEST_FAILURE';
export const PERMISSIONS_STATUSES_SET = 'PERMISSIONS_STATUSES_SET';
