import Config from 'react-native-config';

import { SCREENS, SCREENS_INFO } from './screens';
import { ALL_APPS, HOME_APPS, CONTACT_DETAILS_APPS } from './apps';
import { APP_ICON, FLEX, NUMBERS, SIZES, STRINGS } from './constants';

const {
	LOCALE,
	GOOGLE_MAPS_API_KEY,
	URL_WIKIHOW,
	URL_INFO_DATA,
	URL_ABOUT_US,
	EMAIL_ACCOUNT,
	FAKE_PHOTO_NAME_TEMPLATE,
	FAKE_PHOTO_NB,
	KEY_PUZZLE_A,
	KEY_PUZZLE_B,
	KEY_PUZZLE_C,
	KEY_PUZZLE_D,
} = Config;

export {
	ALL_APPS,
	HOME_APPS,
	CONTACT_DETAILS_APPS,
	APP_ICON,
	FLEX,
	NUMBERS,
	SIZES,
	STRINGS,
	SCREENS,
	SCREENS_INFO,
	LOCALE,
	GOOGLE_MAPS_API_KEY,
	URL_WIKIHOW,
	URL_INFO_DATA,
	URL_ABOUT_US,
	EMAIL_ACCOUNT,
	FAKE_PHOTO_NAME_TEMPLATE,
	FAKE_PHOTO_NB,
	KEY_PUZZLE_A,
	KEY_PUZZLE_B,
	KEY_PUZZLE_C,
	KEY_PUZZLE_D,
};
