import Config from 'react-native-config';

import { ALL_APPS, HOME_APPS } from './apps';
import { APP_ICON, FLEX, STRINGS, SCREENS } from './constants';

const {
	LOCALE,
	GOOGLE_MAPS_API_KEY,
	URL_WIKIHOW,
	URL_INFO_DATA,
	URL_ABOUT_US,
	KEY_PUZZLE_A,
	KEY_PUZZLE_B,
	KEY_PUZZLE_C,
	KEY_PUZZLE_D,
} = Config;

export {
	ALL_APPS,
	HOME_APPS,
	APP_ICON,
	FLEX,
	STRINGS,
	SCREENS,
	LOCALE,
	GOOGLE_MAPS_API_KEY,
	URL_WIKIHOW,
	URL_INFO_DATA,
	URL_ABOUT_US,
	KEY_PUZZLE_A,
	KEY_PUZZLE_B,
	KEY_PUZZLE_C,
	KEY_PUZZLE_D,
};
